### ISSUE TITLE
users-authentication Add devise to project for user authentication and creation of user table

### ISSUE THREAD

**Issue by cherhuber** [Scatterplot/SCRUM-Project#10]
-Add devise to gem project
-Install devise
-create user database

**Comment by cherhuber** [comment]
This was added and pushed.  Did we want to have code reviews before we push?

**Comment by Scatterplot** [comment]
Cheryl, I believe we should only review changes before merging the clone back into master, unless two or more of us are working on a feature clone simultaneously.
